package edu.grinnell.csc207.soundsofsorting;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;

import edu.grinnell.csc207.soundsofsorting.events.SortEvent;

/**
 * The Control Panel houses the GUI for interacting with the Sounds of
 * Sorting application.
 */
public class ControlPanel extends JPanel {
    /** The frames-per-second that the program should render at */
    private static final int FPS = 20;
    
    /**
     * Generates a list of sorting events by sorting the given array using the
     * specified sorting algorithm.
     * @param sort the name of the sorting algorithm to use
     * @param arr the array to sort
     * @return the list sorting events generated by sorting the array
     */
    private static List<SortEvent<Integer>> generateEvents(String sort, Integer[] arr) {
        // N.B., make sure to sort a copy of the array, so we don't mutate the original!
        Integer[] copy = Arrays.copyOf(arr, arr.length);
        switch (sort) {
            case "Selection":
                return Sorts.selectionSort(copy);
            case "Insertion":
                return Sorts.insertionSort(copy);
            case "Bubble":
                return Sorts.bubbleSort(copy);
            case "Merge":
                return Sorts.mergeSort(copy);
            case("Quick"):
                return Sorts.quickSort(copy);
            default:
                throw new IllegalArgumentException("generateEvents");
        }
    }
    
    /**
     * Generates the named scale.
     * @param name the name of the scale
     * @return a new Scale object that contains the desired scale
     */
    public static Scale generateScale(String name) {
        switch (name) {
            case "Pentatonic":
                return Scale.bMinorPentatonic;
            case "Chromatic":
                return Scale.chromatic;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    /**
     * @param fps the frames-per-second the simulation should run in
     * @return the period (in milliseconds) between steps of the simulation
     */
    private static int toPeriod(int fps) {
        return 1000 / fps;
    }
    
    private Scale scale;
    private ArrayPanel panel;
    private boolean isSorting;
    
    /**
     * Constructs a new ControlPanel.
     * @param notes the Notes object that this control panel manages
     * @param panel the ArrayPanel that this panel renders to
     */
    public ControlPanel(NoteIndices notes, ArrayPanel panel) {
        scale = Scale.bMinorPentatonic;
        notes.initialize(scale.size());
        this.panel = panel;
        
        ///// The sort selection combo box /////
        JComboBox<String> sorts = new JComboBox<>(new String[] {
            "Selection",
            "Insertion",
            "Bubble",
            "Merge",
            "Quick"
        });
        add(sorts);
        
        ///// The scale selection combo box /////
        JComboBox<String> scales = new JComboBox<>(new String[] {
            "Pentatonic",
            "Chromatic"
        });
        add(scales);
        
        ///// The make scale button /////
        JButton makeScaleButton = new JButton("Make Scale");
        makeScaleButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (!isSorting) {
                    scale = generateScale((String) scales.getSelectedItem());
                    notes.initialize(scale.size());
                    ControlPanel.this.panel.repaint();
                }
            } 
        });
        add(makeScaleButton);
        
        ///// The play button /////
        JButton playButton = new JButton("Play");
        playButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (isSorting) {
                    return;
                }
                isSorting = true;
                
                // 1. Create the sorting events list
                List<SortEvent<Integer>> events =
                    generateEvents(sorts.getSelectedItem().toString(), notes.getNotes());
               
                // 2. Play back the events on the (original) array
                // NOTE: The Timer class repetitively invokes a method at a
                //       fixed interval.  Here we are specifying that method
                //       by creating an _anonymous subclass_ of the TimeTask
                //       class. You can interpret the run() method as the
                //       method that fires on every "tick" of the program.
                Timer timer = new Timer();
                timer.schedule(new TimerTask() {
                    private int index = 0;
                    
                    @Override
                    public void run() {
                        Integer[] arr = notes.getNotes();
                        if (index < events.size()) {
                            SortEvent<Integer> e = events.get(index++);
                            // 1. Apply the next sort event.
                            e.apply(arr);
                            // 2. Play the corresponding notes denoted by the
                            //    affected indices logged in the event. Also,
                            //    Highlight the affected indices
                            for (int i : e.getAffectedIndices()) {
                                scale.playNote(arr[i], notes.isHighlighted(i));
                                notes.highlightNote(i);
                            }
                            // 3. Suggest a repaint to make the changes visible
                            panel.repaint();
                        } else {
                            this.cancel();
                            panel.repaint();
                            isSorting = false;
                        }
                    }
                }, 0, toPeriod(FPS));

            }

        });
        add(playButton);
    }
}
